package promise.app.error

class AppError(cause: Throwable) : Exception(cause)
