package promise.app_base.error

class AppError(cause: Throwable) : Exception(cause)
