package promise.app_base.error;

import java.lang.System;

@kotlin.Metadata(mv = {1, 1, 15}, bv = {1, 0, 3}, k = 1, d1 = {"\u0000\u001c\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0003\n\u0000\n\u0002\u0010\u000e\n\u0002\b\u0002\u0018\u00002\u00060\u0001j\u0002`\u0002B\u000f\b\u0016\u0012\u0006\u0010\u0003\u001a\u00020\u0004\u00a2\u0006\u0002\u0010\u0005B\r\u0012\u0006\u0010\u0003\u001a\u00020\u0006\u00a2\u0006\u0002\u0010\u0007\u00a8\u0006\b"}, d2 = {"Lpromise/app_base/error/AppError;", "Ljava/lang/Exception;", "Lkotlin/Exception;", "cause", "", "(Ljava/lang/Throwable;)V", "", "(Ljava/lang/String;)V", "appbase_debug"})
public final class AppError extends java.lang.Exception {
    
    public AppError(@org.jetbrains.annotations.NotNull()
    java.lang.String cause) {
        super();
    }
    
    public AppError(@org.jetbrains.annotations.NotNull()
    java.lang.Throwable cause) {
        super();
    }
}